name: "EKS Deployment - CD"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Set the default directory for ALL steps in this job
    defaults:
      run:
        working-directory: terra-infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      # STEP 1: LOGIN FIRST
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::087097353362:role/github-actions
          aws-region: us-west-2

      # STEP 2: VERIFY LOGIN (Helpful for debugging)
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Bootstrap S3 Backend
        run: |
          # Create the bucket if it doesn't exist
          if ! aws s3api head-bucket --bucket devops-capstone-ifedi 2>/dev/null; then
            echo "Bucket does not exist. Creating..."
            aws s3api create-bucket \
              --bucket devops-capstone \
              --region us-west-2 \
              --create-bucket-configuration LocationConstraint=us-west-2
            
            # Enable Versioning (Best Practice for State)
            aws s3api put-bucket-versioning \
              --bucket devops-capstone \
              --versioning-configuration Status=Enabled
              
            # Block Public Access
            aws s3api put-public-access-block \
              --bucket devops-capstone \
              --public-access-block-configuration "BlockPublicAcl=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
          else
            echo "Bucket already exists."
          fi  

      # STEP 3: INITIALIZE
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve



     
      