name: "Devops Capstone - CD"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Set the default directory for ALL steps in this job
    defaults:
      run:
        working-directory: terra-infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      # STEP 1: LOGIN FIRST
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::087097353362:role/github-actions
          aws-region: us-east-1

      # STEP 2: VERIFY LOGIN (Helpful for debugging)
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # STEP 3: INITIALIZE
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve



     
      